class SymbolTable {
    - List< Map<String, Id> > : symbols

    + addContext()
    + deleteContext()
    + searchId()
    + searchLocalId()
    + addId()
}

class abstract Id {
    - String id
    - Enum type
    - Boolean initialized
    - 

}